### ISSUE TITLE
can wyrmoost mod run with terraforged ?

### ISSUE THREAD

**Issue by Brooker69** [Kqy9/Wyrmroost#298]
**Logs:** {Link(s) to GitHub Gist, Pastebin, etc with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Do this
 2. Then do that
 3. ...

**Description of issue:**

**Comment by Kqy9** [comment]
first of all please do not ask questions in the github. Thats what we have a discord for.

Secondly, should work fine.
