### ISSUE TITLE
Can't mount Overworld Drake to tame it

### ISSUE THREAD

**Issue by BEARPOW3R** [Kqy9/Wyrmroost#300]
Hello! I've encoutered an issue when trying to tame Overworld Drake. After approaching, I can't mount it. I've been trying on different maps and the problem remains. I've also test-tamed all other dragons and the issue only applies to the Overworld Drakes.
I attached the list of all other mods I'm currently using.
![List of Mods](https://user-images.githubusercontent.com/81311170/130104682-2e5fc930-3510-449b-aecf-081ad5b60b58.png)

**Comment by GundunUkan** [comment]
Did you make sure to put a saddle on it first? You can't mount wild unsaddled drakes.

**Comment by BEARPOW3R** [comment]
Ohhh, I forgot about this o.o' now I feel stupid Q.Q Sorry  for trouble!

**Comment by GundunUkan** [comment]
Haha no worries
