### ISSUE TITLE
Silver Glider sounds like a heartbeat instead of whistling

### ISSUE THREAD

**Issue by Happenstance-14** [Kqy9/Wyrmroost#307]
Minecraft 1.16.5
forge 36.2.0
Wyrmroost 1.2.11

One of the Silver Glider's idle sounds seems to be misplaced. Instead of a whistle, it plays an ominous heartbeat. Needless to say, this is quite unsettling.

The file in question is idle3.ogg

**Comment by GundunUkan** [comment]
It isn't missing, it's an attempt at a 'purr', admittedly a failed one. Silver Glider sounds have been redone along with the visual aspect of that dragon so it will be gone next version.
